# Libraries for Data Analysis in python
## Library means <span style="color:green">already written codes of people.<span>

***Libraries for <font color='red'>data analysis</font> in python that  we are going to discuss are given below:***

### 1.  Numpy
### 2. Pandas
### 3. Matplotlib
### 4. Seaborn


# Importing Liraries
## Import <font color='red'>numpy</font> as <span style="color:green">np<span>  
    # to import complete library
**from <font color='red'>numpy</font> import <span style="color:green">arange<span>**  
    
    # to import a specific function from a library       


# Numpy
**<span style="color:green">  it mainly deals with array processing , matrices and mathematical operations. <span>**
#### it is also a universal standard for working with numerical data in python.


# Creating <font color='blue'>array</font> using numpy

In [2]:
import numpy as np

np.array([2,4,6,8,10])       #  Creating an array by using numpy library

array([ 2,  4,  6,  8, 10])

In [3]:
arr_1 = np.array([2,4,6,8,10,12,14,16,18,20]) # storing array in a variable
arr_1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
type(arr_1)      # to find the type of array stored in variable in output nd means n-dimension.

numpy.ndarray

In [5]:
type(np.array)     #builtin_function_or_method object is not subscriptable is a “typeerror” that occurs when you try to call a built-in function the wrong way.

builtin_function_or_method

# Dimensions of an array
[1,2,3,4,5]

Array that has multiple columns and a single row is called <span style="color:green"> one dimensional array<span>.
    
[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
    
Array that has multiple columns and multiple rows is called  <font color='red'>two dimensional array</font>.
    
>**A <font color='green'>Vector</font> is a single dimensional array.**
    
>**Array with two dimensions is also called <font color='red'>Matrix</font>.**
    
>**3-array or higher than 3-d arrays are commonly called <span style="color:green"> Tensor <span>.**
    
>**<font color='red'>Axis</font> is also known as dimension.**
    
>**Length of an array is the number of data points.**
    


# One Dimensional Array

In [63]:
arr_1 = np.array([2,4,6,8,10,12,14,16,18,20])
arr_1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
type(arr_1)            # By this we can check the type of an array.

numpy.ndarray

In [11]:
ones = np.ones(10)      # by this you can write no. zeros of your choice.
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
zeros = np.zeros(6)     # by this you can write no. zeros of your choice.
zeros

array([0., 0., 0., 0., 0., 0.])

### Default data type is floating points.
### For Specifying data type of data points.

In [39]:
np.ones(5,dtype = np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [10]:
arr_1.ndim             # its use to identify dimension of array.

1

In [13]:
arr_1.shape             # tells no of values in the arrays     &     also it means ROWS INTO COLUMNS.

(10,)

In [14]:
arr_1.size               # it also tells the no of values in the arrays.

10

In [15]:
np.var(arr_1)           # calculate variance of a numpy  array.

33.0

In [16]:
np.diff(arr_1)          # calculate the difference between subsequents values of numpy array.

array([2, 2, 2, 2, 2, 2, 2, 2, 2])

In [17]:
np.std(arr_1)           # calculate the standard daviation of numpy array.

5.744562646538029

In [18]:
np.cumsum(arr_1)        # calculate the cumulative sum of the elements in numpy array.

array([  2,   6,  12,  20,  30,  42,  56,  72,  90, 110], dtype=int32)

In [19]:
np.max(arr_1)           # return the maximum value of numpy array.

20

In [20]:
np.argmax(arr_1)       # return the index of the elements with maximum value in the numpy array.

9

In [21]:
np.nonzero(arr_1)       # return the indices(index of values in the array) of the nonzero elements in numpy array.

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),)

In [5]:
stringArray = np.array(['Apple', 'Ball', '', 'Dog'])
stringArray

array(['Apple', 'Ball', '', 'Dog'], dtype='<U5')

In [7]:
stringResult = np.nonzero(stringArray)      # return indices(means index of value in array)of non-empty elements in stringArray
print('Indices of non-empty elements in stringArray:', stringResult)

Indices of non-empty elements in stringArray: (array([0, 1, 3], dtype=int64),)


In [22]:
np.linspace(2,6,8)           # its mean it shows 8 num.b/w 2 & 6 .

array([2.        , 2.57142857, 3.14285714, 3.71428571, 4.28571429,
       4.85714286, 5.42857143, 6.        ])

In [23]:
arr_2 = np.arange(20)        # it will show no.from 0 to you choice of number.
arr_2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [77]:
arr_4 = np.linspace(4,9,5)    # 1st = first point, 2nd = last point , 3rd = total no of value between these two points.
arr_4

array([4.  , 5.25, 6.5 , 7.75, 9.  ])

In [78]:
arr_1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [87]:
a = np.array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [88]:
b = a.reshape(3,3)
b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [93]:
np.reshape(a,newshape = (3,3),order = 'A')

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

# ORDERS IN NUMPY
 ## there are four types of orders in numpy
        
>**C** Is Contiguous layout. Mathematically speaking,<font color='red'>row major</font>.

>**F** Is Fortran contiguous layout. Mathematically speaking, <span style="color:green">column major<span>.

>**A** Is any order. Generally  <font color='red'>don't use this</font>.

>**K** Is keep order. Generally <span style="color:green">don't use this<span>.

In [98]:
arr_1 = np.array([2,  4,  6,  8, 10, 12, 14, 16, 18, 20])
arr_1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

# indexing & Slicing
## Slicing in python means taking elements from one given index to another given index.

>We pass slice instead of index like this: [start:end].

>We can also define the step, like this: [start:end:step].

In [100]:
print(arr_1[3])   # we can call a value by its index

8


In [101]:
print(arr_1[0:6])   # 1st argument = first index , 2ns argument =  last index , it will print values fron index 0 to index 6.

[ 2  4  6  8 10 12]


In [102]:
print(arr_1[3: ])      # 1st argument = first index , 2ns argument = black space which it will print from 3 to onward go the last index.

[ 8 10 12 14 16 18 20]


In [103]:
print(arr_1[ :7])    # 1st argument = blank means its index 0 , 2nd argument = last index , means it will print from index 0 to the index 7.

[ 2  4  6  8 10 12 14]


In [104]:
print(arr_1[::-1])     # by this we can print our array in reverse order from last index to the first index.

[20 18 16 14 12 10  8  6  4  2]


In [106]:
print(arr_1[1:6:2])   # 1st argument = first index , 2nd argument = last index , 3rd argument = give value by skipping 1 value.

[ 4 10]


In [ ]:
print(arr_1[1:6:3])  # 1st argument = first index , 2nd argument = last index , 3rd argument = give value by skipping 2 value.

In [108]:
print(arr_1[1: :2])  # 1st argument = first index , 2nd argument = space (means its the last index od the array) , 3rd argument = give value by skipping 1 value.

[ 4  8 12 16 20]


In [110]:
print(arr_1[-3:-1])     # it will give values from the index 3 from the end to index 1 from the end:

[16 18]


### Slicing on the basis of conditions

In [124]:
(arr_1[arr_1>4])     # in this we give condition like it will print value that are greater than 4.

array([ 6,  8, 10, 12, 14, 16, 18, 20])

In [126]:
print(arr_1>8)     # by this method condition will give answer in boolean datatype in which(Fasle not fulfil the given condition & True means it  fulfil the given condition).

[False False False False  True  True  True  True  True  True]


In [127]:
print(arr_1!=10)   # by this method condition will give answer in boolean datatype in which(Fasle not fulfil the given condition & True means it  fulfil the given condition).

[ True  True  True  True False  True  True  True  True  True]


In [128]:
print(arr_1<12)   # same as the above one. 

[ True  True  True  True False False False False False False]



# Two Dimensional Array

In [113]:
arr_5 = np.array([[2,4,6,8,10] , [12,14,16,18,20]])
arr_5

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [114]:
type(arr_5)       # here we can check the type of an array.

numpy.ndarray

In [116]:
print(arr_5[1, 1:4]) # 1st argument = index of ROW from the array, 2nd argument = (1:4) in this 1st digit is the first index of value from that ROW and 2nd digit is the last index of the value from that ROW. 

[14 16 18]


In [117]:
print(arr_5[0:2, 2])      # it the same like above cell but chenge in position.
# 1st argument = (0:2) in this 1st digit is the first index of value from that ROW and 2nd digit is the last index of the value from that ROW.
# 2nd argument = index of ROW from the array

[ 6 16]


In [119]:
print(arr_5[0:2, 1:4])    
# 1st argument = (0:2) 1st digit is the index of first value ,and 2nd digit the index of last value(will be given from first ROW of the matrix).
# 1st argument = (1:4) 1st digit is the index of first value ,and 2nd digit the index of last value(will be given from second ROW of the matrix).

[[ 4  6  8]
 [14 16 18]]


In [27]:
arr_5.shape      # in output 1st argument = ROWS  & 2nd argument =  COLUMNS.

(2, 5)

In [28]:
arr_5.ndim        # it will show the dimensions of an array.

2

In [29]:
arr_5.size         # it will show no. of values in array

10

In [30]:
arr_5 = np.array([[2,7,6,89,10] , [12,17,15,18,11]])
arr_5

array([[ 2,  7,  6, 89, 10],
       [12, 17, 15, 18, 11]])

In [37]:
print("Arrays before sorting",arr_5)
arr_5.sort()                             #it can sort an array
print("Arrays after sorting",arr_5)


Arrays before sorting [[ 2  6  7 10 89]
 [11 12 15 17 18]]
Arrays after sorting [[ 2  6  7 10 89]
 [11 12 15 17 18]]


In [32]:
arr_5.sum()              # we can sum the vales in array

187

In [49]:
arr_5 = np.array([[2,4,6,8,10],[12,14,16,18,20]])
arr_5[1,:]                           #This will return all elements of 1st row in the form of array

array([12, 14, 16, 18, 20])

In [59]:
arr_rand = np.random.rand(2,5)       # it will generate an array with all random elements
arr_rand

array([[0.86900138, 0.6391025 , 0.42187219, 0.77297601, 0.51075049],
       [0.18685823, 0.46886823, 0.58761476, 0.14873368, 0.07223567]])

In [74]:
arr_i = np.identity(3)   # it will return an identity matrix , in code value(that i put 3) means it make value-by-value matrix means 3-by-3 matrix. 
print(arr_i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [62]:
#Arithmatic operation on 2d-array
A = np.array([[1,2,3],[4,6,2]]) #array with size 3x3

#Scalar operation - It will operate with scalar to each element of an array
print(A+2)
print(A-4)
print(A*3)
print(A/2)
print(A**2)

[[3 4 5]
 [6 8 4]]
[[-3 -2 -1]
 [ 0  2 -2]]
[[ 3  6  9]
 [12 18  6]]
[[0.5 1.  1.5]
 [2.  3.  1. ]]
[[ 1  4  9]
 [16 36  4]]


In [63]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)     # 1st argument = no. of ROWS ,2nd arguments = no. of COLUMNS.

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [134]:
a = np.array((1,2,3))      # it will Stack arrays in sequence depth wise (along third axis).
b = np.array((2,3,4))
np.dstack((a,b))

array([[[1, 2],
        [2, 3],
        [3, 4]]])

In [135]:
np.ma.dstack((a,b))     # it will Stack arrays in sequence depth wise (along third axis) & then give an array in masked form(True if it is MaskType, False otherwise). 

masked_array(
  data=[[[1, 2],
         [2, 3],
         [3, 4]]],
  mask=[[[False, False],
         [False, False],
         [False, False]]],
  fill_value=999999)

In [136]:
np.vstack((a,b))     # it will give an array in vertical form 

array([[1, 2, 3],
       [2, 3, 4]])

In [137]:
np.hstack((a,b))       # it will give array in horizontal form  

array([1, 2, 3, 2, 3, 4])

In [150]:
i = np.arange(1,21).reshape(4,5)
i

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [161]:
i.sum()    # it will sum all the value in the array

210

In [163]:
i.sum(axis = 0)       # it will sum values in array column wise( axis = 0 = horizontal which means it will sum all the value in matrixs column wise).    

array([34, 38, 42, 46, 50])

In [164]:
i.sum(axis = 1)       # it will sum values in array row wise( axis = 1 = vertical which meansit will sum all the value in matrixs row wise)

array([15, 40, 65, 90])

In [151]:
np.vsplit(i,4)      # will split the array in vertical split( means that will form only no.of columns in array not no. of rows)

[array([[1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20]])]

In [155]:
np.hsplit(i,5)   # will split the array in 5 horizontal array( means that will form only no.of ROWS in array not no. of COLUMNS)

[array([[ 1],
        [ 6],
        [11],
        [16]]),
 array([[ 2],
        [ 7],
        [12],
        [17]]),
 array([[ 3],
        [ 8],
        [13],
        [18]]),
 array([[ 4],
        [ 9],
        [14],
        [19]]),
 array([[ 5],
        [10],
        [15],
        [20]])]

In [156]:
Data = np.array([2,4])
Data

array([2, 4])

In [158]:
ones = np.ones(2,dtype = int)
ones

array([1, 1])

In [159]:
Data + ones      #it will sum both column wise

array([3, 5])

In [160]:
Data * ones      #it will multiply both column wise

array([2, 4])

# Three Dimensional Array

In [47]:
a = np.array([[[1, 0, 3],[2, 0, 0],[0, 4, 5]]])
a

array([[[1, 0, 3],
        [2, 0, 0],
        [0, 4, 5]]])

In [29]:
type(a)           # here we can check the type of an array.

numpy.ndarray

In [48]:
a.ndim               # it will the show no. of dimensions of an array.    

3

In [31]:
a.shape              #1st argument = no. of dimension , 2nd argument = no. of ROWS , 3rd argument = no.of COLUMNS

(3, 3)

In [32]:
a2 = np.arange(12)   # arange(12) means it will give 12 value from 0 to 11.
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
a3 = np.arange(24).reshape(2,3,4)   #arange(24) means it will give 12 value from 0 to 23.
a3
# reshape (2,3,4)  in with 1st argument = dimension or axis, 2nd argument = no, of ROWS, 3rd argument = no. ofCOLUMNS.

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [34]:
a3.shape       # 1st argument = Dimensions , 2nd argument = ROWS , 3rd argument = COLUMNS

(2, 3, 4)

In [35]:
a4 = np.array([[[2,4,6,8,10] , [12,14,16,18,20] , [22,24,26,28,30]]])
a4

array([[[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20],
        [22, 24, 26, 28, 30]]])

In [36]:
a4[0 , 1]         #1st argument = dimension which is 0 here that means it will only makr horizontal array , 2nd argument = index of ROWS

array([12, 14, 16, 18, 20])

In [37]:
a4[0, 2]         #1st argument = dimension which is 0 here that means it will only make horizontal array , 2nd argument = index of ROWS

array([22, 24, 26, 28, 30])

In [38]:
a4[0,2,2]        # 1st argument = dimension(0) , 2nd argument = index of ROW(2) , 3rd argument = index of the value(2)

26

In [39]:
a4[0,1,3]        # 1st argument = dimension(0) , 2nd argument = index of ROW(1) , 3rd argument = index of the value(3)

18

In [40]:
a4[0, 0:2, 0:3]       #we can take specific rows & columns from array
   # 1st argument = Dimension of the array 
    #2nd argument(0:2) = in which 1st digit means the index of ROW & 2nd digit means the index of value from that ROW.
    #3rd argument(0:3) = in which 1st digit means the index of COLUMN & 2nd digit means the index of value from that COLUMN.
    

array([[ 2,  4,  6],
       [12, 14, 16]])

In [41]:
a4[0, 1:2, 2:3]       #we can take specific rows & columns from array
    # 1st argument = Dimension of the array 
    # 2nd argument(1:2) = in which 1st digit means the index of ROW & 2nd digit means the index of value from that ROW.
    # 3rd argument(2:3) = in which 1st digit means the index of COLUMN & 2nd digit means the index of value from that COLUMN.
    

array([[16]])

In [42]:
np.random.randint(2,10,20)
   # 1st argument = first value,
    #2nd argument = last value , 
    #3rd argument = no . value that we make between first value and last value.

array([3, 4, 5, 2, 2, 3, 6, 9, 8, 2, 5, 8, 8, 2, 3, 6, 2, 8, 2, 5])

In [43]:
np.random.randint(3,20,10)
# 1st argument = first value,
# 2nd argument = last value ,#
#3rd argument = no . value that it make between first value and last value.

array([10, 11, 13, 19,  7,  3, 15,  9,  6,  6])

In [44]:
np.cumsum(a4)    # calculate the cumulative sum of the elements in numpy array
 # means it will sum first and second digit = firstvalue,
    # then that first value sum up with third digit = second value,
    # then that second value sum up with forth digit = third value,   and so on it will goes to the last digit.

array([  2,   6,  12,  20,  30,  42,  56,  72,  90, 110, 132, 156, 182,
       210, 240], dtype=int32)

In [74]:
a    # here we call our first array

array([[[1, 0, 3],
        [2, 0, 0],
        [0, 4, 5]]])

In [50]:
np.nonzero(a)        # return the indices of the nonzero elements in numpy array
  #in output 1st array = show dimension of newly formed array 
    # 2nd array = it show index of values ROW wise in the matrix(like in 1st row we have 1 at index0, then in 2nd row we have 2 at index 0 , in 3rd Row we have 4 at index 1 and 5 at index 2 then at last it will go to 1st row where we have 3 at index 2)
    # 3rd array = it show index od values COLUMN wise in the matrix( like in 1st column we have 1 at index 0, then in 2nd column we have 4 at index 2, then in 3rd column we have 3 at index 0 then it goes to first column for second calue in 1st column which is 2 at index 1 and then we have a value in 3rd column which is 5 at index 2)

(array([0, 0, 0, 0, 0], dtype=int64),
 array([0, 0, 1, 2, 2], dtype=int64),
 array([0, 2, 0, 1, 2], dtype=int64))

In [51]:
np.transpose(np.nonzero(a))    # Here we have a simple transpose of nonzero functions's output which convert COLUMNS into ROWS.

array([[0, 0, 0],
       [0, 0, 2],
       [0, 1, 0],
       [0, 2, 1],
       [0, 2, 2]], dtype=int64)

In [54]:
np.argsort(a, axis = 1)     # in argsort with axis = 1 function work as The elements in the first column are sorted first followed by the second column and so on. All columns are sorted independently of each other.
# like in our matrix(a)in 1st column of matrix(a) we have smallest value 0 at index 2 then we have 1 at index 0 then we have 2 at index 1,in output first column is like that.
# then in 2nd column of matrix(a) we have smallest value 0 at index then we have aother value 0 at index 1 then we have value 4 at index 2 .in output second column is like that,
# then in 3rd column of our matrix(a) we have smallest value 0 at index 1 then we have 3 at index 1 and then we have 5 at index 2, in output the third column is made like this.

array([[[2, 0, 1],
        [0, 1, 0],
        [1, 2, 2]]], dtype=int64)

In [55]:
np.diff(a)   # this function we compare values in a row by themselves
            # like in first ROW (0-1=-1) &(3-0=3) then in second ROW (0-2=-2)&(0-0=0) then in third ROW(4-0=4)&(5-4=1)

array([[[-1,  3],
        [-2,  0],
        [ 4,  1]]])

In [58]:
np.max(a)       # this will gives us the maximun value from the matrix(a).

5

In [64]:
np.std(a , axis = 0)     # here axis = 0 means STD( standard daviation ) is along the individual COLUMNS of the rows of matrix.

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [68]:
np.std(a , axis = 1)      # here axis = 1 means STD( standard daviation ) is along the ROWS (means the answer the array will be onlyy columns not in rows)

array([[0.81649658, 1.88561808, 2.05480467]])

In [67]:
np.var(a)         #it will consider (a) to be flattened (works on all the axis).  

3.3333333333333335

In [69]:
np.var(a,axis = 0)                     #axis = 0 means variance along the column 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [70]:
np.var(a,axis = 1)                  #axis = 1 means variance along the row.

array([[0.66666667, 3.55555556, 4.22222222]])

In [73]:
np.argmax(a)         ##it will consider (a) to be flattened (works on all the axis). it will gives the index of maximum value.

8

In [75]:
np.argmax(a, axis = 0)              #axis = 0  it will gives the index of maximum values along the column 

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [76]:
np.argmax(a, axis = 1)                        #axis = 0  it will gives the index of maximum values along the ROWS.

array([[1, 2, 2]], dtype=int64)

## Concatenation
#### Concatenate a sequence of arrays along an existing axis.
###### Concatenation can also be form by giving it axis.

> **Axis = 0** , mean concatenate the matrices <font color='red'>horizontally</font>.

> **Axis = 1** , mean concatenate the matrices <span style="color:green">vertically<span>.
    
> The <font color='red'>length</font> of arrays should be same in <font color='blue'>Concatenation</font>    
    
> use **one [ ] bracket** for 1-d array.
    
> use **two [ [  ] ] brackets** for 2-d array.
    
> use **three[ [ [  ] ] ] brackets** for 3-d array.

In [170]:
A= np.array([1,2,3,4,5])     # it will merge these two arrays in one array
B = np.array([6,7,8,9,10])
np.concatenate((B,A))

array([ 6,  7,  8,  9, 10,  1,  2,  3,  4,  5])

In [167]:
C = np.array([[1,2,3,4,5],[11,12,13,14,15]])     # it will merge these two matrices in on array ( 2-d array)
D = np.array([[6,7,8,9,10],[16,17,18,19,20]])
np.concatenate((C,D))

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])

In [168]:
C = np.array([[1,2,3,4,5],[11,12,13,14,15]])       # it will concatenate the two arrays horizontally (in2-d array)
D = np.array([[6,7,8,9,10],[16,17,18,19,20]])
np.concatenate((C,D),axis = 0 )

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])

In [169]:
C = np.array([[1,2,3,4,5],[11,12,13,14,15]])       # it will concatenate the two arrays vertically ( in2-d array)
D = np.array([[6,7,8,9,10],[16,17,18,19,20]]) 
np.concatenate((C,D),axis = 1 )

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [171]:
C = np.array([[[1,2,3,4,5],[11,12,13,14,15]]])       # it will concatenate the two arrays horizontally ( in 3-d array)
D = np.array([[[6,7,8,9,10],[16,17,18,19,20]]])
np.concatenate((C,D),axis = 0 )

array([[[ 1,  2,  3,  4,  5],
        [11, 12, 13, 14, 15]],

       [[ 6,  7,  8,  9, 10],
        [16, 17, 18, 19, 20]]])

In [172]:
C = np.array([[[1,2,3,4,5],[11,12,13,14,15]]])       # it will concatenate the two arrays vertically ( in 3-d array)
D = np.array([[[6,7,8,9,10],[16,17,18,19,20]]])
np.concatenate((C,D),axis = 1 )

array([[[ 1,  2,  3,  4,  5],
        [11, 12, 13, 14, 15],
        [ 6,  7,  8,  9, 10],
        [16, 17, 18, 19, 20]]])